try:
  globalChat: true # Будет ли сообщение отправляться всем игрокам?
  radius: 100 # Радиус отправки сообщения (только если параметр "global_chat" = true)
me:
  globalChat: true
  radius: 100
onlineBook:
  enabled: true
  reset: false
hideTags:
  enabled: true

perms.check: false # Нужно ли проверять, имеет ли игрок право использовать рп-команды