try:
  globalChat: true # Will messages from try to be sent to all players?
  radius: 100 # The radius of sending messages (only if the "global_chat" parameter = true)
me:
  globalChat: true
  radius: 100
onlineBook:
  reset: false
hideTags:
  enabled: true

perms.use: false # Whether to check whether the player has the right to use rp commands