name: RPplugin
version: '${project.version}'
main: ru.siaw.free.rpplugin.RPplugin
author: tom8hawk
website: siaw.ru

commands:
  rppl:
    desription: Commands of the plugin itself/business trips
  try:
    desription: The /try command
  me:
    desription: The /me command